### ISSUE TITLE
test_gdasapp_C96C48_ufs_hybatmDA_gdas_prepatmiodaobs_202402240000 fails

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GDASApp#1624]
Job `test_gdasapp_C96C48_ufs_hybatmDA_gdas_prepatmiodaobs_202402240000` failed in the 20250417 run of stable-nightly.  The gdas_prepatmiodas log file contains the error message
```
    from pyiodaconv import bufr
ImportError: cannot import name 'bufr' from 'pyiodaconv'
```
following the execution of each `ush/ioda/bufr2ioda/bufr2ioda*py` converter.  

The same error occurs when this test is executed on Hera, Hercules, and Orion.

Note:  To enable g-w CI tests from GDASApp we must build GDASApp inside g-w PR [#3587](https://github.com/NOAA-EMC/global-workflow/pull/3587) with `WORKFLOW_TESTS="ON"` in the user environment.

**Comment by RussTreadon-NOAA** [comment]
g-w PR [#3571](https://github.com/NOAA-EMC/global-workflow/pull/3571) moved the following section from `prepatmiodaobs.sh`
```
###############################################################
# setup python path for ioda utilities
# shellcheck disable=SC2311
pyiodaPATH="${HOMEgfs}/sorc/gdas.cd/build/lib/python${PYTHON_VERSION}/"
PYTHONPATH="${pyiodaPATH}:${PYTHONPATH}"
export PYTHONPATH
```
to `ush/load_ufsda_modulefiles.sh`

`echo "$PYTHONPATH is ${PYTHONPATH}"` statements added to scripts executed by `prepatmiodaobs.sh` shows that  `PTYHONPATH`  includes `${HOMEgfs}/sorc/gdas.cd/build/lib/python${PYTHON_VERSION}/`.  Directory `pyiodaconv` exists in this `PYTHONPATH`

Why then do the bufr2ioda converter scripts generate the error
```
    from pyiodaconv import bufr
ImportError: cannot import name 'bufr' from 'pyiodaconv'
```

**Comment by RussTreadon-NOAA** [comment]
g-w PR [#3571](https://github.com/NOAA-EMC/global-workflow/pull/3571) consolidated the setting of `$PTYHONPATH` for GDASApp applications in `ush/load_ufsda_modules.sh`
```
###############################################################
# setup python path for ioda utilities
# TODO: a better solution should be created for setting paths to package python scripts
# shellcheck disable=SC2311
pyiodaPATH="${HOMEgfs}/sorc/gdas.cd/build/lib/python${PYTHON_VERSION}/"
gdasappPATH="${HOMEgfs}/sorc/gdas.cd/sorc/iodaconv/src:${pyiodaPATH}"
PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}:${gdasappPATH}"
export PYTHONPATH
```

Prior to g-w PR [#3571](https://github.com/NOAA-EMC/global-workflow/pull/3571) [`dev/jobs/snowanl.sh`](https://github.com/NOAA-EMC/global-workflow/pull/3571/files#diff-6675040ee871d90eb764af347289e678992a09fdf9a909c4ba0bcb7126156a5a) and [`dev/jobs/esnowanl.sh`](https://github.com/NOAA-EMC/global-workflow/pull/3571/files#diff-28212e43e6af4ab6bcd43b7c73a3c71459b0aa59745a5abea4740069f7552b3a) contained the above scripting.  

[`dev/jobs/prepatmiodaobs.sh`](https://github.com/NOAA-EMC/global-workflow/pull/3571/files#diff-493bb84e9093a441065e08798faffebabdf57ca72c6e1218190f14a9604b8a5f) had similar scripting but without the `gdasappPATH` line.   Below is the scripting previously found in `prepatmiodaobs.sh`
```
###############################################################
# setup python path for ioda utilities
# shellcheck disable=SC2311
pyiodaPATH="${HOMEgfs}/sorc/gdas.cd/build/lib/python${PYTHON_VERSION}/"
PYTHONPATH="${pyiodaPATH}:${PYTHONPATH}"
export PYTHONPATH
```

When GDASApp g-w CI is run following g-w PR [#3571](https://github.com/NOAA-EMC/global-workflow/pull/3571), the C96C48_ufs_hybatmDA gdas_prepatmiodaobs job fails on Hera with
```
    from pyiodaconv import bufr
ImportError: cannot import name 'bufr' from 'pyiodaconv' (/scratch1/NCEPDEV/da/Russ.Treadon/CI/GDASApp/stable/20250417/global-workflow/sorc/gdas.cd/sorc/iodaconv/src/pyiodaconv/__init__.py
```
This `__init__.py` file is zero length
```
-rw-r--r-- 1 Russ.Treadon da 0 Apr 17 00:36 /scratch1/NCEPDEV/da/Russ.Treadon/CI/GDASApp/stable/20250417/global-workflow/sorc/gdas.cd/sorc/iodaconv/src/pyiodaconv/__init__.py
```

As a test remove `gdasappPATH` from `ush/load_ufsda_modules.sh` so that it reads
```
###############################################################
# setup python path for ioda utilities
# TODO: a better solution should be created for setting paths to package python scripts
# shellcheck disable=SC2311
pyiodaPATH="${HOMEgfs}/sorc/gdas.cd/build/lib/python${PYTHON_VERSION}/"
PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}:${pyiodaPATH}"
export PYTHONPATH
```

Rerun 
- C96C48_ufs_hybatmDA 20240224 00Z gdas_prepatmiodaobs 
- C96C48_hybatmaerosnowDA 20211220 18Z gdas_snowanl
- C96C48_hybatmaerosnowDA 20211220 18Z enkfgdas_esnowanl
 
Each job successfully ran to completion.

The modified `ush/load_ufsda_modules.sh` was committed to [`RussTreadon-NOAA:bugfix/gdasapp_gwtests`](https://github.com/RussTreadon-NOAA/global-workflow/tree/bugfix/gdasapp_gwtests) at [`4e33848`](https://github.com/RussTreadon-NOAA/global-workflow/commit/4e338489cb82dac631441934cd2f7054ec24bb32).

Tagging @ClaraDraper-NOAA , @jiaruidong2017, @CoryMartin-NOAA for awareness.

**Comment by RussTreadon-NOAA** [comment]
Resolved by g-w PR [#3587](https://github.com/NOAA-EMC/global-workflow/pull/3587).  Close this issue.
